### ISSUE TITLE
How can we use the compute_DRT on our own data?

### ISSUE THREAD

**Issue by jianzuo** [MaximeVH/DistributedRelaxationTimes.jl#2]
Hello,
Can you help to registrate the library so that we can try to compute DRT on our own data?
Thank you very much!

**Comment by MaximeVH** [comment]
The package will be registered this week, after some slight adjustments. In the meantime, the code can be used by cloning the repository

**Comment by jianzuo** [comment]
Thank you @MaximeVH . 
I tried to clone the repository, but got some errors with SqExponentialKernel(), seems can not find what it is?

**Comment by jianzuo** [comment]
Will DRT be registered? Thank you!

**Comment by MaximeVH** [comment]
> Will DRT be registered? Thank you!

I have now registered the package, which required a name change to "DistributedRelaxationTimes". This package will be available in the registry for installation after the mandatory three day waiting period
