### ISSUE TITLE
verifying DRT calculation on simple R//C circuit

### ISSUE THREAD

**Issue by jianzuo** [MaximeVH/DistributedRelaxationTimes.jl#5]
Hi,
I tried a simple verification on a resistor-capacitor in parallel circuit, with R=100, C=0.001,
the theoretical time constant is tau=RC=0.1.

For verification of DRT calculation, I first generated the EIS data by simulating the circuit, here is the data
I used: 
[rq_test (copy).csv](https://github.com/MaximeVH/DistributedRelaxationTimes.jl/files/13922516/rq_test.copy.csv)
generated by following python code:

```
import numpy as np
f_start=1e6
f_stop=0.01
f_decades = np.log10(f_start) - np.log10(f_stop)
pts_decade = 7
f_range = np.logspace(np.log10(f_start), np.log10(f_stop), num=np.int64(np.around(pts_decade*f_decades)), endpoint=True)
w_range = 2 * np.pi * f_range

def RQ(w, R, Q):
    val = 1/R + Q * 1j * w
    return 1/val
rq1 = RQ(w=w_range, R=100, Q=1e-3)
```

 And here is the DRT calculation code:
```
Z_data = CSV.read("rq_test (copy).csv", DataFrame, header=1)
frequencies = Z_data[:,1]

measurements = Z_data[:,2] .+ (Z_data[:,3] .* im)

#Calculacte the DRT using default keyword argument values.
peak_taus, peak_amplitudes, taus_out, drt =  compute_DRT(frequencies, measurements)
```
The obtained value for peak_taus is 0.01673453293928837, much smaller than the true value.
Can you give some hints on where I did wrong? Thank you very much!

**Comment by Matheus-gif** [comment]
Have you tried changing the lambda value? I don't have more time today, but the default lambda value used for the package is 0.01. Try running the following lines (in Julia) and see if it works. I can also try it tomorrow if needed.

```julia
# Find the optimal lambda parameter using Saccoccio et al.'s Re-Im cross-validation test functions, this may take several minutes.
@time λ_opt =  find_optimal_lambda(frequencies, measurements)

#Calculacte the DRT using default keyword argument values.
peak_taus, peak_amplitudes, taus_out, drt =  compute_DRT(frequencies, measurements, λ = λ_opt)

# Diplay the DRT graph
plot_DRT(peak_taus, peak_amplitudes, taus_out, drt, lab = "example", color = "green")
```

Hope it helps.

**Comment by jianzuo** [comment]
Hi,
Thank you very much for the suggestions.
I have run the code, the result is 0.01606 for peak_taus.
